# Generated by Django 3.1 on 2022-10-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221008_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'СуперАдмин'), ('admin', 'Админ'), ('manager', 'Менеджер'), ('default', 'Обычный')], default='default', max_length=100, verbose_name='Role'),
        ),
    ]
